name: Publish Docker Image

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Defina a versão do Java que você está usando
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests  # Compila o projeto Maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Usuário do GitHub
          password: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação

      - name: Build the Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/voting-app-backend:latest

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/voting-app-backend:latest
