# .github/workflows/ci.yml
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Passo 3: Compilar o projeto com Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
